---

###
### Validate required defines
###
- name: "({{ cluster.name }}) ensure cluster name is defined"
  assert:
    that:
      - cluster.name is defined
      - cluster.name | length > 0
    msg: "Cluster 'name' is not defined, but required"

- name: "({{ cluster.name }}) ensure cluster ssh key is defined"
  assert:
    that:
      - >-
        (cluster.ssh_pub_key is defined and cluster.ssh_pub_key | length > 0) or
        (kops_default_ssh_pub_key is defined and kops_default_ssh_pub_key | length > 0)
    msg: "Cluster 'ssh_pub_key' or kops_default_ssh_pub_key is not defined, but one of them is required"

- name: "({{ cluster.name }}) ensure cluster s3 bucket name is defined"
  assert:
    that:
      - cluster.s3_bucket_name is defined
      - cluster.s3_bucket_name | length > 0
    msg: "Cluster 's3_bucket_name' is not defined, but required"

- name: "({{ cluster.name }}) ensure workers array is defined"
  assert:
    that:
      - cluster.workers is defined
      - cluster.workers | length > 0
    msg: "No worker nodes are defined. Your cluster will be useless"

- name: "({{ cluster.name }}) ensure workers array is defined correctly"
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    msg: "No worker 'name' is defined"
  with_items:
    - "{{ cluster.workers }}"

###
### Validate availability zones
###
- name: "({{ cluster.name }}) ensure master availability zones are within defined availability zones"
  assert:
    that:
      - item in cluster.az | default(kops_default_az)
    msg: >-
      Master availability zone '{{ item }}' is not within
      '[{{ cluster.az | default(kops_default_az) | join(',') }}]'
  with_items:
    - >-
      {%- if 'master' in cluster and 'az' in cluster.master -%}
      {{ cluster.master.az }}
      {%- else -%}
      {{ kops_default_master_az }}
      {%- endif -%}

- name: "({{ cluster.name }}) ensure bastion availability zones are within defined availability zones"
  assert:
    that:
      - item in cluster.az | default(kops_default_az)
    msg: >-
      Bastion availability zone '{{ item }}' is not within
      '[{{ cluster.az | default(kops_default_az) | join(',') }}]'
  with_items:
    - >-
      {%- if 'bastion' in cluster and 'az' in cluster.bastion -%}
      {{ cluster.bastion.az }}
      {%- else -%}
      {{ kops_default_bastion_az }}
      {%- endif -%}

- name: "({{ cluster.name }}) ensure worker availability zones are within defined availability zones"
  assert:
    that:
      - >-
        {%- for az in item.az | default(kops_default_worker_az) -%}
        ('{{ az }}' in cluster.az | default(kops_default_az)) and
        {% endfor %} true
    msg: >-
      Worker availability zones '{{ item.az | default(kops_default_worker_az) | join(',') }}'
      is not within '[{{ cluster.az | default(kops_default_az) | join(',') }}]'
  with_items:
    - "{{ cluster.workers }}"

###
### Validate encryptionConfig setting
###
- name: "({{ cluster.name }}) ensure encryptionConfig enabled is boolean"
  assert:
    that:
      - item.enabled is defined
      - item.enabled | type_debug == 'bool'
    msg: "enabled should be true or false"
  with_items:
    - >-
      {%- if cluster.encryptionConfig is defined and 'enabled' in cluster.encryptionConfig -%}
      {{ cluster.encryptionConfig }}
      {%- else -%}
      {{ kops_default_encryptionConfig }}
      {%- endif -%}

- name: "({{ cluster.name }}) ensure encryptionConfig image is defined"
  assert:
    that:
      - item.image is defined
      - item.image | length > 0
    msg: "No 'image' is defined"
  with_items:
    - >-
      {%- if cluster.encryptionConfig is defined and 'enabled' in cluster.encryptionConfig and
      cluster.encryptionConfig.enabled -%}
      {{ cluster.encryptionConfig }}
      {%- else -%}
      {{ kops_default_encryptionConfig }}
      {%- endif -%}

- name: "({{ cluster.name }}) ensure encryptionConfig kms_id is defined"
  assert:
    that:
      - item.kms_id is defined
      - item.kms_id | length == 36
    msg: "Check 'kms_id' is defined and length is 36"
  with_items:
    - >-
      {%- if cluster.encryptionConfig is defined and 'enabled' in cluster.encryptionConfig and
      cluster.encryptionConfig.enabled -%}
      {{ cluster.encryptionConfig }}
      {%- else -%}
      {{ kops_default_encryptionConfig }}
      {%- endif -%}
