---

###
### Gather ec2 security facts
###

- name: "({{ cluster.name }}) set ec2 security filter"
  set_fact:
    kops_ec2_security_groups_filters:
      # - key: group-name
      #   val: "{{ to_be_defined }}"
      - key: vpc-id
        val: "{{ kops_vpc_id }}"

- name: Get Security Group ID
  ec2_group_facts:
    filters: "{{ kops_ec2_security_groups_filters | get_attr('key', 'val') }}"
    region:  "{{ cluster.region | default(kops_default_region) }}"
  register: _kops_api_additional_sgs

- name: Print variable
  debug:
    msg: EC2 Security Group ID {{ _kops_api_additional_sgs }}

- name: Set Security ID fact
  set_fact:
    kops_api_additional_sgs: "{{ kops_api_additional_sgs |
      combine( { item.group_name: {'group_id': item.group_id} } ) }}"
  with_items: "{{ _kops_api_additional_sgs.security_groups }}"
  when: item | length > 0


- name: Print variable
  debug:
    msg: Final List {{ kops_api_additional_sgs }}
    # "{{ _kops_api_additional_sgs }}"
