---

###
### Gather ec2 security facts
###

- name: "({{ cluster.name }}) set ec2 security filter"
  set_fact:
    kops_ec2_security_groups_filters:
      - key: vpc-id
        val: "{{ kops_vpc_id }}"

- name: Get Security Group ID
  ec2_group_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ kops_aws_profile | default(omit) }}"
    filters: "{{ kops_ec2_security_groups_filters | get_attr('key', 'val') }}"
    region: "{{ cluster.region | default(kops_default_region) }}"
  register: _kops_api_additional_sgs

- name: Set Security Groups ID fact
  set_fact:
    kops_api_additional_sgs: "{{ kops_api_additional_sgs |
      combine( { item.group_name: item.group_id } ) }}"
  no_log: true
  with_items: "{{ _kops_api_additional_sgs.security_groups }}"
  when: item | length > 0
