---

- name: "({{ cluster.name }}) ensure project build directory is present"
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: "({{ cluster.name }}) generate kubernetes templates and ssh key"
  template:
    src: "{{ item }}.j2"
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/{{ item }}"
    mode: 0644
  loop:
    - cluster.yml
    - instance-groups.yml
    - encryption-config.yml
    - ssh-key.pub

- name: "({{ cluster.name }}) generate shell scripts"
  template:
    src: "{{ item }}.j2"
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/{{ item }}"
    mode: 0755
  loop:
    - kops-create.sh
    - kops-update.sh
    - kops-validate.sh
    - kops-delete.sh
    - kops-kubectl-config.sh
    - kubectl-context.sh
