---

- name: "({{ cluster.name }}) ensure project build directory is present"
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: "({{ cluster.name }}) generate kubernetes templates and ssh key"
  template:
    src: "{{ item }}.j2"
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/{{ item }}"
    mode: 0644
  loop:
    - cluster.yml
    - instance-groups.yml
    - encryption-config.yml
    - ssh-key.pub

- name: "({{ cluster.name }}) verify kops_dockerconfig_creds for dockerhub"
  uri:
    url: "{{ kops_dockerconfig_creds.url | default(kops_default_dockerconfig_creds.url )}}"
    user: "{{ kops_dockerconfig_creds.user }}"
    password: "{{ kops_dockerconfig_creds.token }}"
    force_basic_auth: true
    timeout: 5
  register: _kops_dockerconfig_login
  failed_when: "'token' not in _kops_dockerconfig_login.json"
  when: >
    ( kops_dockerconfig_creds is defined ) and
    ( 'user' in kops_dockerconfig_creds ) and
    ( 'token' in kops_dockerconfig_creds )

- name: "({{ cluster.name }}) generate shell scripts"
  template:
    src: "{{ item }}.j2"
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/{{ item }}"
    mode: 0755
  loop:
    - kops-create.sh
    - kops-update.sh
    - kops-validate.sh
    - kops-delete.sh
    - kops-kubectl-config.sh
    - kubectl-context.sh
