---
name: CI build
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Files
        run: |
          make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [2.9, latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Asserts with for ansible=${{ matrix.version }}
        run: |
          make test ANSIBLE_VERSION=${{ matrix.version }}
